networks:
  proxyma-net:
    driver: bridge

services:
  node-1:
    build: .
    container_name: node-1
    user: "${HOST_UID}:${HOST_GID}"
    networks:
      - proxyma-net
    volumes:
      - ./deploy/data/node-1:/app/data
    ports:
      - "8081:8081"

  node-2:
    build: .
    container_name: node-2
    user: "${HOST_UID}:${HOST_GID}"
    networks:
      - proxyma-net
    volumes:
      - ./deploy/data/node-2:/app/data
    ports:
      - "8082:8082"

  node-3:
    build: .
    container_name: node-3
    user: "${HOST_UID}:${HOST_GID}"
    networks:
      - proxyma-net
    volumes:
      - ./deploy/data/node-3:/app/data
    ports:
      - "8083:8083"
