name: Proxyma CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
jobs:
  build-and-test:
    name: Lint, Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run Tests
        run: make test

      - name: Build Binary
        run: make build

      - name: Smoke Test Binary
        run: ./proxyma --help
